### PR TITLE
Add support for Azure, OpenAI, Palm, Anthropic, Cohere, Replicate Models - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for models from all the above mentioned providers using litellm https://github.com/BerriAI/litellm

TLDR: log10 gets:
- more models out of the box 
- instant integration of new models by modifying the `model` param (Easy to add models in the future, just change the model param)

Here's a sample of how it's used:
```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@nqn @treppers can you take a look at this PR when you get the chance? Happy to add more docs/testing if this initial commit looks good

**Comment by nqn** [comment]
Hi @ishaan-jaff - so sorry I completely missed this! Taking a look

**Comment by nqn** [comment]
Hi @ishaan-jaff - we reviewed the PR and doesn't exactly capture the intended use of our LLM classes. So closing for now

**Comment by ishaan-jaff** [comment]
@nqn was there something missing on litellm for your LLM classes ?

**Comment by nqn** [comment]
@ishaan-jaff Just that we have our own base LLM class, and inserting another wrapper/indirection within the openai one doesn't fit our design.

**Comment by krrishdholakia** [comment]
@nqn would your problem be solved if we just added litellm as a separate class / provider?

**Pull request closed without merging**
